---

name: Cause airflow production to refresh DAGs

on:
  push:
    branches:
      - ci
  #pull_request:
    #branches:
      #- production
    #types:
      #- closed

jobs:
  deployment:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
