---

name: Cause airflow production to refresh DAGs

on: push

#on:
  #pull_request:
    #branches:
      #- production
    #types:
      #- closed

jobs:
  deployment:
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      

      - name: Configure 1Password Connect
        uses: 1password/load-secrets-action/configure@v1
        with:
          # Persist the 1Password Connect URL for next steps. You can also persist
          # the Connect token using input `connect-token`, but keep in mind that
          # this will grant all steps of the job access to the token.
          connect-host: ${{ secrets.OP_CONNECT }}
          connect-token: ${{ secrets.OP_API_TOKEN}}

      - name: Load web hook secrets
        uses: 1password/load-secrets-action@v1
        with:
          # Export loaded secrets as environment variables
          export-env: true
        env:
          WEBHOOK_KEY: op://${{ secrets.OP_VAULT_ID  }}/Airflow\ Webhook/password

      - name: Print masked secret
        run: echo "WEBHOOK_KEY: $WEBHOOK_KEY"

      - name: Load web hook secrets
        uses: 1password/load-secrets-action@v1
        with:
          # Export loaded secrets as environment variables
          export-env: true
        env:
          WEBHOOK_ADDRESS: op://${{ secrets.OP_VAULT_ID }}/Airflow\ Webhook/smee/address


      #- name: Load secret
        #id: op-load-secret
        #uses: 1password/load-secrets-action@v1
        #env:
          #OP_CONNECT_TOKEN: ${{ secrets.OP_API_TOKEN }}

      - name: Invoke deployment hook
        uses: distributhor/workflow-webhook@v2
        env:
          webhook_url: ${{ env.WEBHOOK_ADDRESS }}
          webhook_secret: ${{ env.WEBHOOK_KEY }}
          curl_opts: '-H "X-Webhook-Key: ${{ env.WEBHOOK_KEY }}"'
          # data: '{ "webhook_key": "${{ env.WEBHOOK_KEY }}" }'
